image: maven:latest

variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SSL_NO_VERIFY: "true"

#build:
#  stage: build
#  script:
#    - mvn compile
#  only:
#    - biblioteka

deploy:
  stage: deploy
  script:
    - mvn deploy
#    - ssh-add <(echo "$SSH_PRIVATE_KEY")sm_92F1HzCjT7YeJh5aL
    - (cd ../shop-assistant-mvn-repo ; git init)
    - (cd ../shop-assistant-mvn-repo ; git remote add origin https://wwojcik235621:%CI_PUSH_TOKEN%@git.e-science.pl/wwojcik235621/81e_WWojcik_Maven.git)
    - (cd ../shop-assistant-mvn-repo ; git fetch -p)
    - (cd ../shop-assistant-mvn-repo ; git checkout gitlabRunner -f)
    - (cd ../shop-assistant-mvn-repo ; git add -A)
    - (cd ../shop-assistant-mvn-repo ; git commit -m "gitlab runner realise")
    - (echo "git push origin gitlabRunner")
    - (cd ../shop-assistant-mvn-repo ; git push origin gitlabRunner)
  only:
    - biblioteka